name: Sync Fork

on:
  schedule:
    # Daily at 8:20 UTC
    - cron: '20 8 * * *'
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - run: gh repo sync leukosaima/mkdocs-material -b master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
