name: Sync Fork

on:
  schedule:
    # Daily at 8:20 UTC
    - cron: '20 8 * * *'
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync fork
        id: sync
        run: |
          OUTPUT=$(gh repo sync leukosaima/mkdocs-material -b master)
          echo "OUTPUT=[$OUTPUT]"
          if [ -n "$OUTPUT" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger workflows
        if: steps.sync.outputs.changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build.yml',
              ref: 'master'
            });

            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'documentation.yml',
              ref: 'master'
            });
